---
- ansible.builtin.include_tasks: "common/tasks/read_host_inventory.yml"
  when: remote_inventory is not defined

- name: check if node already configured for service component
  ansible.builtin.meta: end_host
  when: configured_service | default(true)
        and remote_inventory["configured_service"]

- ansible.builtin.include_tasks: "common/tasks/new_revision.yml"

- name: build bridge_vlan
  set_fact:
    bridge_vlan: "vlan{{bridge_pvid}}"

- name: build dhcp_relay_interface
  ansible.builtin.set_fact:
    dhcp_relay_interfaces: "{{ dhcp_relay_interfaces | default(
                              [ { 'id': bridge_vlan } ] )
                              + [ { 'id': item } ] }}"
  with_items: "{{ north_interfaces }}"

- name: build snmp config
  ansible.builtin.set_fact:
    snmp_listeners:
      - id: "{{ ansible_host }}"
        vrf: "mgmt"

- name: Service config
  nvidia.nvue.service:
    revid: "{{ revision.revid }}"
    state: merged
    data:
      dhcp_relay:
        - id: "default"
          interface: "{{ dhcp_relay_interfaces }}"
          server:
            - id: "{{ dhcp_relay_server }}"
      snmp_server:
        enable: "on"
        listening_address: "{{ snmp_listeners }}"
        readonly_community:
          - id: "{{ vault_snmp_readonly_community }}"
            access: "{{ snmp_readonly_community_access }}"
        system_contact: "{{ system_contact }}"
        system_location: "{{ system_location }}"
      dns:
        - id: "mgmt"
          server: "{{ dns_servers }}"
      syslog:
        - id: "mgmt"
          server: "{{ syslog_servers }}"
      ntp:
        - id: "mgmt"
          server: "{{ ntp_servers }}"

- ansible.builtin.include_tasks: "common/tasks/apply_revision.yml"

- name: set configured service flag variable
  ansible.builtin.set_fact:
    temp_fact:
      configured_service: true

- ansible.builtin.include_tasks: "common/tasks/write_host_inventory.yml"
