- name: Wait for connection
  wait_for:
    port: 22
  delegate_to: localhost

- name: Copy over benchmarking files
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: '0755'
  loop:
    - get-iris.sh
    - run_iris.sh

- name: copy over gpu_benchmark.sh
  ansible.builtin.template:
    src: gpu_benchmark.sh.j2
    dest: ~/gpu_benchmark.sh
    mode: '0755'

- name: Install python3.8-venv Ubuntu
  apt:
    name: python3.8-venv
    state: present
  become: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed
  when: ansible_distribution == 'Ubuntu'

- name: Install python3.8-venv Rocky
  yum:
    name: python3.8-venv
    state: present
  become: true
  when: ansible_distribution == 'Rocky'

- name: Install docker Ubuntu
  apt:
    name: docker.io
    state: present
  become: true
  register: result
  retries: 5
  delay: 30
  until: result is not failed
  when: ansible_distribution == 'Ubuntu'

- name: Install docker Rocky
  yum:
    name: docker.io
    state: present
  become: true
  when: ansible_distribution == 'Rocky'
