- name: Automatically create and destroy VMs
  hosts: localhost
  tags:
    - create
  vars:
    images: ["ubuntu-focal-20.04-nogui"]
    vm_name: "Meerkat_Benchmark_2"
    key_name: diz41711
      
  pre_tasks:
    - package:
        name: python3-openstacksdk
        state: present
      become: true

    - name: Query openstack
      openstack.cloud.compute_flavor_info:
        ram: "<20000"
      register: flavor_list

    - name: Generate list
      set_fact:
        flavors: "{{ flavors | default([]) + [item.name | string] }}"
      with_items:
        - "{{ flavor_list.openstack_flavors }}"

    - name: Remove GPU flavors
      set_fact:
        flavors: "{{ flavors | reject('search', 'g-') | list }}"

    - name: Print flavors
      debug: var=flavors

    - name: Print images
      debug: var=images
      
    - name: Print VM name
      debug:
        msg: "{{ vm_name }}"

  tasks:
    - name: Create VMs
      include_role: 
        name: create_vm
      with_nested:
        - "{{ flavors }}"
        - "{{ images }}"
    
- name: Storage benchmark
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  tags:
    - benchmark
  roles:
    - role: storage_benchmark


- name: delete VMs
  hosts: localhost
  roles:
    - destroy_vm
