- name: HEPScore benchmark
  block:
    - name: Template metrics sending script
      become: true    
      ansible.builtin.template:
        src: send_to_victoria.sh.j2
        dest: /usr/local/bin/send_to_victoria.sh
        mode: a+x

    - name: Add apptainer repo (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:apptainer/ppa
        state: present

    - name: Install packeages for HEPScore
      become: true
      ansible.builtin.package:
        name: 
          - python3 
          - python3-pip 
          - git 
          - jq
          - apptainer
        state: present

    - name: Install HEPScore
      ansible.builtin.pip:
        name: git+https://gitlab.cern.ch/hep-benchmarks/hep-score.git

    - name: Make results directory
      ansible.builtin.file:
        path: results
        state: directory

    - name: Run HEPScore
      ansible.builtin.command: ~/.local/bin/hepscore -m singularity results

    - name: Send score to VictoriaMetrics
      ansible.builtin.command: /usr/local/bin/send_to_victoria.sh
      register: return_code
      changed_when: return_code.rc == 0

  rescue:
    - name: Print errored VM
      debug:
        msg: HEPScore failed to run
