- name: Run local storage benchmark
  shell: "./benchmark.sh -p /home/{{ user }} -s local"

- name: Run volume storage benchmark
  shell: ./benchmark.sh -p /mnt/volume -s volume

- name: Run manila share benchmark
  shell: ./benchmark.sh -p /home/{{ user }}/manila{{ vm_count }} -s manila
