name: Cloud DNS tests

on: 
  push:
    branches:
      - master
  pull_request:
    paths:
      - "reverseforwardrecord/**"
      - ".github/workflows/get_dns_records.yaml"

jobs:
  test_and_lint:
    runs-on: ["ubuntu-22.04"]
    strategy:
      matrix:
        python-version: ["3.x", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reverseforwardrecord/requirements.txt

      - name: Format code
        uses: psf/black@stable
        with:
          src: "reverseforwardrecord"

      - name: Run tests
        run: cd reverseforwardrecord/ && python3 -m pytest .

      - name: Analyse with pylint
        run: |
          pylint reverseforwardrecord
